# Dockerfile-multistage
# ------- stage_1 starts here ------- #
# This base image python:3.7 with size 1.02GB is used to install packages
# FROM Base image python and givee this stage a name Builder
FROM python:3.7 AS builder

# Make a Working Directory
WORKDIR /app

# Copy the requirements to this working directory
COPY requirements.txt .

# Install whatever is in requirements.txt file
RUN pip install -r requirements.txt

# ------- stage_1 ends here ------- #

# ------- stage_2 starts here ------- #
# This base image python:3.7-slim with size 125MB
FROM python:3.7-slim
WORKDIR /app
# Copy the installed package from stage_1 to this final image
COPY --from=builder /usr/local/lib/python3.7/site-packages/ /usr/local/lib/python3.7/site-packages/
COPY . .
ENTRYPOINT [ "python3", "run.py" ]